spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecom_app
    username: root
    password: Pass@1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update     # ✅ keep only one ddl-auto
    show-sql: true
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQLDialect
  data:
    redis:
      host: localhost
      port: 6379

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000

app:
  upload:
    product-dir: uploads
    review-dir: reviews

